version: '3.3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:5-apache
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    depends_on:
      - mysql
    ports:
      - '8000:80'
    environment:
      WP_HOME: http://localhost:3001
      WP_DEFAULT_THEME: smooth-js
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
  mysql_data:
